### PR TITLE
rename OVM_ETH symbol and name

### PR DESCRIPTION
**Pull request by K-Ho**
## Questions
- 
-
-

### Fixes
- Fixes # [Link to Issue]

## Contributing Agreement

- [ ] I have read and understood the [Optimism Contributing Guide and Code of Conduct](https://github.com/ethereum-optimism/optimism-monorepo/blob/master/.github/CONTRIBUTING.md) and am following those guidelines in this pull request.

### CODE REVIEW

**Review by smartcontracts — APPROVED** [review]

**Review by tynes — APPROVED** [review]

**Comment by tynes** [comment]
I do have a question around what is ETH and what is WETH on Optimism - right now it seems like WETH is ETH and ETH is WETH?

**Comment by maurelian** [comment]
@tynes as currently implemented, all ETH on L2 is actually WETH. I believe @ben-chain's plans are to make it so that you can interact with ETH as if it were both WETH and ETH.

**Review by maurelian — APPROVED** [review]
I don't object, so I'll approve, but what is the rationale?

**Comment by smartcontracts** [comment]
> I don't object, so I'll approve, but what is the rationale?

Since the L2 should be backed by L1 security, the ETH on L2 should generally be treated the same as on L1. I also think it's a bit less confusing to say "you have ETH on L2" rather than "you have this different wrapped ETH asset on L2 that can be redeemed at a 1:1 rate for ETH on L1"

**Comment by maurelian** [comment]
@ben-chain please review!

Also, a question: could this have any implications for other components?

**Review by ben-chain — APPROVED** [review]
I think this is the right move, approving!

**Pull request merged**
