### PR TITLE
script: serve state dump

### PR DESCRIPTION
**Pull request by tynes**
## Description

A script for serving the state dump on localhost. Usage:

```bash
$ yarn build
$ yarn serve
```

This depends on python3 being installed locally

## Contributing Agreement

- [x] I have read and understood the [Optimism Contributing Guide and Code of Conduct](https://github.com/ethereum-optimism/optimism-monorepo/blob/master/.github/CONTRIBUTING.md) and am following those guidelines in this pull request.

### CODE REVIEW

**Comment by ben-chain** [comment]
Ran into troubles with this due to having my `python` be 2.7 whereas `python3` is my v3.  Was unable to simply alias to solve this.

Is this intended to be run locally or as a part of docker?  It seems like implementing this in JS would decrease the local dependencies required.

**Comment by tynes** [comment]
I'll update this to work better. Not sure why python2 is still the default python on osx, its been sunset for over a year at this point

**Comment by tynes** [comment]
Note that there is a way to get around this with how I wrote the script

```
$ PYTHON=python3 ./scripts/serve_dump.sh
```

**Comment by tynes** [comment]
This should now work for python2 or python3

**Review by karlfloersch — APPROVED** [review]
LGTM!

**Pull request merged**
