### PR TITLE
refactor: use AddressZero instead of ZERO_ADDRESS

### PR DESCRIPTION
**Pull request by snario**
Uses a more standardized zero address.

### CODE REVIEW

**Comment by maurelian** [comment]
`ZERO_ADDRESS` also appears in 20 or so other *.ts files according to my search, so I think we should make this change to all of them at once.

**Comment by TransmissionsDev** [comment]
TIL!

**Review by karlfloersch — COMMENTED** [review]
Nice change & I do think we should change it in a bunch of places

**Comment by smartcontracts** [comment]
@karlfloersch I made #329 as a "Good First Issue" for people on discord to tackle.

**Comment by vaibhavchellani** [comment]
Will this PR fix #329 or is it up for taking?

**Pull request closed without merging**
