### PR TITLE
Naming cleanup

### PR DESCRIPTION
**Pull request by axchu**
- Fixes https://github.com/ethereum-optimism/roadmap/issues/285

## Contributing Agreement

- [x] I have read and understood the [Optimism Contributing Guide and Code of Conduct](https://github.com/ethereum-optimism/optimism-monorepo/blob/master/.github/CONTRIBUTING.md) and am following those guidelines in this pull request.

### CODE REVIEW

**Review by kfichter — APPROVED** [review]
LGTM. Doesn't seem to break any interfaces, so should be good for merge.

**Comment by kfichter** [comment]
Oh sorry didn't realize this was still a draft!

**Comment by axchu** [comment]
@kfichter mentioned some downstream changes might be necessary

**Review by kfichter — COMMENTED** [review]
Looks good to me. Going to mark this as "mergeable; breaking" since it might break things downstream. Need to double check whether this is the case or not.

**Pull request closed without merging**
